### ISSUE TITLE
Convenience function to add an ni:/// @id to json LD without one

### ISSUE THREAD

**Issue by melvincarvalho** [digitalbazaar/jsonld-signatures#1]
As per mailing list discussion, something like:

What I usually do is hash the normalized form, which I think is possibly the most logical thing to do?

```
if @id
return
else
  @id = sha256(normalized(json-ld))
```

http://lists.w3.org/Archives/Public/public-credentials/2014Dec/0028.html

**Comment by dlongley** [comment]
Very old -- closing, reopen if it makes sense.
