### ISSUE TITLE
Is it possible to create proof chains?

### ISSUE THREAD

**Issue by skradha26** [digitalbazaar/jsonld-signatures#101]
I would like to create proof chains where multiple parties can sign a proof. For example: If a party is transferring ownership of an asset to another party and both parties need to sign the contract. Is it possible to use proof chains?

Please let me know if there is a way to post questions instead of issues. Thanks.

**Comment by dlongley** [comment]
There is not an implementation for proof chains in this library yet. However, it seems that your use case may be better served by proof sets instead. Proof chains are for signing another party's signature. I think, in this case, you want two (or more) parties to sign the same document. Proof sets, which are implemented by this library, are for that use case.

IIRC, to add additional proofs to a document, simply sign the same document multiple times with different keys, i.e., each party to a contract should sign the document, producing a separate proof. All of the proofs can be expressed as an array under the `proof` property -- and if you're using this library to do all of the signatures, existing signatures under the `proof` property will be preserved when new proofs are added.

**Comment by mandyvenables** [comment]
@skradha26 Does the comment above answer your question? If so, please close the issue. Thanks!

**Comment by skradha26** [comment]
Yes. Thankyou.
