### ISSUE TITLE
Extract signature suites to separate repos

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/jsonld-signatures#105]
Similar to how the `crypto-ld` library is being refactored in PR https://github.com/digitalbazaar/crypto-ld/pull/47, it would make sense to restructure `jsonld-signatures` in the same way. This repo would contain just the general `LinkedDataProof` / `LinkedDataSignature` suites, and the key-specific ones would live in their own separate repos.
A `.use()` style API would let developers just include the suites/key types they care about (without having to bundle the rest).

**Comment by dlongley** [comment]
Yes, something like this should be adopted.

**Comment by dlongley** [comment]
Suites have been extracted to separate repos. Closing.
