### ISSUE TITLE
expansionMap cannot be overridden

### ISSUE THREAD

**Issue by JaceHensley** [digitalbazaar/jsonld-signatures#111]
According to the docs [here](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/ProofSet.js#L41) you can set `expansionMap` to false to drop unmapped fields or provide custom mapper. But the implementation has `expansionMap` always being set to `strictExpansionMap` unless `expansionMap` is false. So only no expansion map OR the strict expansion map is allowed.

I'm happy to make a PR to update this to allow passing a custom expansionMap.

**Comment by DenisPopov15** [comment]
Do we have any updates here? Looks like a bug here.
