### ISSUE TITLE
Publish latest version to NPM

### ISSUE THREAD

**Issue by harlantwood** [digitalbazaar/jsonld-signatures#12]
in particular with bitcoin signing

**Comment by harlantwood** [comment]
\<bump\>

I'm also happy to publish if easier; my npm user is `harlantwood`.

**Comment by dlongley** [comment]
@harlantwood if you can #10 to use `KoblitzSignature2016` we'll do a release with that.

**Comment by harlantwood** [comment]
Updated #10 with the latest sig name.

**Comment by harlantwood** [comment]
#10 is merged, please publish to NPM.

**Comment by harlantwood** [comment]
\<bump\>

As I mentioned above: 

> I'm also happy to publish if easier; my npm user is harlantwood.

**Comment by harlantwood** [comment]
Done.
