### ISSUE TITLE
ProofSet._addToJson fails when error is text

### ISSUE THREAD

**Issue by lemoustachiste** [digitalbazaar/jsonld-signatures#124]
I'm currently experiencing an issue which I am trying to get to the bottom of.
But I noticed that this function https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/ProofSet.js#L342 expects an object as error. 

The error I originally have is `Failed to normalize document` which once sent to this function fails and creates another error: `TypeError: Object.defineProperty called on non-object`. This is because in this case the error is a string.

I don't know if it's an edge-case or something you'd want to fix, but here is the report :)

**Comment by lemoustachiste** [comment]
In all fairness that error as text comes from my own signature suite

**Comment by dlongley** [comment]
Closing as invalid; errors should not be strings but `Error` instances.
