### ISSUE TITLE
Ensure LinkedDataSignature constructor initializes this.signer

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/jsonld-signatures#136]
Subclasses (like the 2020 suite) sometimes pass a `signer` object to the suite constructor, instead of a key.
Make sure that gets initialized in the constructor (this is currently not working).

**Comment by mattcollier** [comment]
In v7.x, `this.signer` was being handled by an intermediate `JwsLinkedDataSignature` class which has been removed.

https://github.com/digitalbazaar/jsonld-signatures/blob/v7.0.0/lib/suites/JwsLinkedDataSignature.js#L42

I'm making a PR for this now.
