### ISSUE TITLE
Add test cases that use new expansionMap capabilities

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/jsonld-signatures#146]
We need new test cases for at least:

1. Failing to sign (catch expansionMap error): A doc with a relative IRI `@id` value.
2. Failing to sign (catch expansionMap error): A doc with a relative IRI `@type` value w/no base IRI set.
3. Failing to sign (catch expansionMap error): A doc with a relative IRI `@type` value w/ base IRI set.

And the same 3 for failing to verify.

**Comment by davidlehn** [comment]
Where do tests go now?  This repo has no tests anymore.  Adding to all the suites would be redundant.

**Comment by dlongley** [comment]
@dmitrizagidulin, can you be of assistance here (where do the tests go)?

**Comment by davidlehn** [comment]
While fixing a [related bug](https://github.com/digitalbazaar/jsonld-signatures/issues/111) it's still unclear where tests should be added.

**Comment by dlongley** [comment]
Closing this issue as there are tests in cryptosuites for this -- just like there are tests in cryptosuites for other behavior. This issue is no longer special ... we still need to add a test suite here to enable better regression testing without having to run against some external cryptosuite tests.
