### ISSUE TITLE
Uncaught signal: 11 Segmentation fault when using the lib

### ISSUE THREAD

**Issue by SanujaLW** [digitalbazaar/jsonld-signatures#168]
We have a server (node - Fastify) running inside GCP Cloud Run and container throws `Uncaught signal: 11 Segmentation fault` when using this package. Increasing memory (8gigs) mitigates the issue to some extent but it still comes up time to time. It does not come when the package is removed.

Other packages used.
```
 "dependencies": {
    "@decentralized-identity/ion-tools": "0.1.1",
    "@digitalcredentials/x25519-key-agreement-key-2020": "^3.0.0",
    "@mattrglobal/bls12381-key-pair": "1.0.0",
    "@mattrglobal/jsonld-signatures-bbs": "1.1.0",
    "@or13/did-jwk": "^0.0.4",
    "@transmute/credentials-context": "0.7.0-unstable.66",
    "@transmute/did-key-bls12381": "0.3.0-unstable.9",
    "@transmute/did-key-ed25519": "0.3.0-unstable.9",
    "@transmute/did-key.js": "0.3.0-unstable.9",
    "@transmute/ed25519-signature-2018": "0.7.0-unstable.66",
    "@transmute/json-web-signature": "0.7.0-unstable.66",
    "fast-crc32c": "^2.0.0",
    "jose": "^4.10.4",
    "@digitalcredentials/ed25519-signature-2020": "^3.0.2",
    "@transmute/vc.js": "0.7.0-unstable.66"
  }
```

**Comment by davidlehn** [comment]
- What version of `jsonld-signatures` and Node.js?
- Just to check, you're saying that installing `jsonld-signatures` in addition to all those packages causes problems?
- Does this happen even if you don't call anything in `jsonld-signatures`?  Is it just while starting up?
- If you are calling something, what is it?
- Can you narrow it down to a simple test case project you could share?
- Causing segfaults is not a common thing in Node.js.  However, the one thing we have found that will almost certainly cause non-deterministic segfaults is mixing native ESM use with the [esm.js](https://www.npmjs.com/package/esm) package.  It's terrible.
- I'd check `npm explain esm` to see if you are using the `esm` package anywhere.  If you are, that's a very likely cause.  The solution is to tear out `esm` from *everything*, or ensure you are not also using native ESM code.  This can be a difficult ask, but `esm` is unmaintained and obsolete so it needs to be removed at some point.
- You'll notice `jsonld-signatures` is just ComonJS, not ESM, but that doesn't stop this bug from happening for reasons I don't understand.  It's a very odd bug that be triggered in odd ways, and it may be that some module loading pattern `jsonld-signatures` uses triggers the problem.
- If you're not using esm.js, then it's difficult to help without more details or, ideally, test code to run.  You could run node in gdb to try and catch the stack traces.  That's how I find these esm.js issues.  It'll crash in some import or require stack.

**Comment by dlongley** [comment]
Closing as not an issue with this library.
