### ISSUE TITLE
How to export jsonld signed credentials 

### ISSUE THREAD

**Issue by projjal1** [digitalbazaar/jsonld-signatures#175]
Hi, I have created signed credential with jsigs.sign(). Now my question is how to export the same for future reference ?
When I try to copy/paste it in jsonld file from console, during verification it gives error.

**Comment by dmitrizagidulin** [comment]
> Hi, I have created signed credential with jsigs.sign(). Now my question is how to export the same for future reference ? When I try to copy/paste it in jsonld file from console, during verification it gives error.

Hi @projjal1. If you're currently doing `console.log(signedVc)`, you should instead do: `console.log(JSON.stringify(signedVc, null, 2))`. 

Does that make sense?

**Comment by projjal1** [comment]
Yes it fixes the issue. What I found is first I need to json.stringify signedVC and then in verifier json.parse the string and then proceed.
