### ISSUE TITLE
Context overriding before canonicalization

### ISSUE THREAD

**Issue by ntn-x2** [digitalbazaar/jsonld-signatures#176]
Hello,

we are trying to implement few crypto suites, one of which would implement the [jcs-eddsa-2022](https://www.w3.org/TR/vc-di-eddsa/#jcs-eddsa-2022) specification. Unfortunately, we have hit what we think is a bug in this library.
The culprit is, specifically, this code snippet:

```ts
function _getProofs({document}) {
  // handle document preprocessing to find proofs
  let proofSet;
  proofSet = jsonld.getValues(document, 'proof');

  // shallow copy proofs and add document context or SECURITY_CONTEXT_URL
  const context = document['@context'] || constants.SECURITY_CONTEXT_URL;
  proofSet = proofSet.map(proof => ({
    '@context': context,
    ...proof
  }));

  return proofSet;
}
```

We are trying to use the JSON canonicalization algorithm, and this means that it treats the `@context` property as any other property in the input document. So now we have the issue that a proof is different between when it is canonicalised for signing and when it is canonicalised for verifying.
This is because when signing, the proofset is empty, hence the `proofSet.map` loop does not run and the context is not set. Upon verifying, the `proofSet.map` loop runs once, and hence the JSON canonicalization produces a different result which results in a failed verification, since the hashes of the two canonicalized proofs (as generated by the `DataIntegrityProof` class) are different.

We wanted to report this bug as this issue requires us to implement a workaround where we simply ignore the `@context` property if we are dealing with a proof canonicalization. We think this is not right as it basically reduces the security guarantees of the signed JSON-LD document to zero.

A related question would then be whether it is expected behaviour to simply set the `@context` property of the proof with either the document context or the security context? What if the proof has a context of its own? This would mean 1. the context is completely ignored when signing, 2. If a non JSON-LD canonicalization algorithm is used, now we have the same problem where the input to the canonicalization function on proof generation is different than the input to the same function on verification.

**Comment by rflechtner** [comment]
While Antonio's point remains a valid concern, I found that the problematic behaviour of the `DataIntegrityProof` suite may be fixed in its own implementation, as it also overwrites the proof's `@context` property, but does so inconsistently (see https://github.com/digitalbazaar/data-integrity/pull/12).

**Comment by dlongley** [comment]
`@digitalbazaar/data-integrity@1.4.1` has been released with the fix from https://github.com/digitalbazaar/data-integrity/pull/12. Please let us know if that addresses the issue. Thanks to @rflechtner for the fix!

**Comment by ntn-x2** [comment]
@dlongley it does fix the issue for non JSON-LD canonicalization, which we use. Thanks for the quick fix. I will close this issue here now.
