### ISSUE TITLE
Add validation to value returned from `getPublicKey`

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/jsonld-signatures#25]
https://github.com/digitalbazaar/jsonld-signatures/blob/multiSignature/lib/jsonld-signatures.js#L709

if `getPublicKey` returns publicKey as undefined, the following error can occur:
'TypeError: Cannot use \'in\' operator to search for \'revoked\' in undefined'

There should be some validation on the result returned from `getPublicKey`

**Comment by dlongley** [comment]
`getPublicKey` removed from the latest API.
