### ISSUE TITLE
Refactor API option style

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/jsonld-signatures#29]
A [comment](https://github.com/digitalbazaar/jsonld-signatures/pull/23#issuecomment-308193545) from an older PR should still be considered:

Looking at the `verify()` API I'm wondering if it might make sense to use a different style for async data options such as `publicKey`:
- Just name the option `publicKey`.
- if it's a function it would have a signature like the `getPublicKey` that was added.
- If it's a promise it resolves to the data.
- If it's an object it's just the data (internally can wrap it in a promise or something as needed).

Advantages are:
- There is just one obvious name.
- Simple case of just data is easy for callers.
- Easy to support the three above styles to pass data.

The code for this is simple but could probably be reused for each option or in other APIs.  Does it make sense to use that sort of style here?

**Comment by dlongley** [comment]
The `getPublicKey` and `publicKey` option has been removed in the new API. A `verifier` option (and a `signer` option) is available for pluggable verification operations that don't directly pass key material.
