### ISSUE TITLE
Refactor to support external signing functions (e.g. HSM/SSM-style signing)

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/jsonld-signatures#30]
The raw signing code used in each suite should be abstracted out into an asynchronous function that takes the private key material. This function could then be overridden by a function that does whatever HSM/SSM/etc. things are necessary to protect the private key material.

**Comment by dmitrizagidulin** [comment]
Assigning myself, per our conversation today.

**Comment by dmitrizagidulin** [comment]
Note to self: coordinate with @gannan08 so this doesn't clash with PR #36
