### ISSUE TITLE
Optimize `createVerifyData` in LinkedDataSignature

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/jsonld-signatures#34]
In this method we compact and then canonize:

https://github.com/digitalbazaar/jsonld-signatures/blob/68e6987c9e111a80ff7ad2bd667a22b4cad1bcd2/lib/suites/LinkedDataSignature.js#L36-L66

Instead, we could expand, store the expanded value, then compact w/expansion flag turned off and then canonize with expansion turned off, eliminating an extra expansion step by reusing the expanded data.

**Comment by davidlehn** [comment]
Implemented in 2.3.1.
