### ISSUE TITLE
code assumes public key already compacted with https://w3id.org/security/v1

### ISSUE THREAD

**Issue by elf-pavlik** [digitalbazaar/jsonld-signatures#4]
- https://github.com/digitalbazaar/jsonld-signatures/blob/f82ab8f143930d7f7cc99d93c1f955f8b5578d93/lib/jsonld-signatures.js#L585
- https://github.com/digitalbazaar/jsonld-signatures/blob/f82ab8f143930d7f7cc99d93c1f955f8b5578d93/lib/jsonld-signatures.js#L320

IMO it should also work if server responds with public key in JSON-LD expanded form, or if one passes key in expanded form via options.

**Comment by dlongley** [comment]
Yeah, somehow some of the public key checks got out of order. For example this code:

https://github.com/digitalbazaar/jsonld-signatures/blob/f82ab8f143930d7f7cc99d93c1f955f8b5578d93/lib/jsonld-signatures.js#L585-L587

Should be moved after the key has been properly framed, which occurs here:

https://github.com/digitalbazaar/jsonld-signatures/blob/f82ab8f143930d7f7cc99d93c1f955f8b5578d93/lib/jsonld-signatures.js#L356-L371

**Comment by elf-pavlik** [comment]
maybe worth adding a test for a key serialized to expanded JSON-LD ?

**Comment by elf-pavlik** [comment]
While trying to run example from README which has

```js
var testPublicKey = {
  '@context': jsig.SECURITY_CONTEXT_URL,
  '@id': 'https://example.com/i/alice/keys/1',
  owner: 'https://example.com/i/alice',
  publicKeyPem: testPublicKeyPem
};
```

I received `[Error: [jsigs.verify] The public key is not a CryptographicKey.]`

After looking at code around line producing error message, I noticed that framing uses `type: 'CryptographicKey'`
https://github.com/digitalbazaar/jsonld-signatures/blob/f82ab8f143930d7f7cc99d93c1f955f8b5578d93/lib/jsonld-signatures.js#L359

after including that type in public key it all worked fine

```js
var testPublicKey = {
  '@context': jsig.SECURITY_CONTEXT_URL,
  '@id': 'https://example.com/i/alice/keys/1',
  '@type':  'CryptographicKey',
  owner: 'https://example.com/i/alice',
  publicKeyPem: testPublicKeyPem
};
```

**Comment by dlongley** [comment]
This has been rewritten and uses framing on verification methods that require look up.
