### ISSUE TITLE
Throw error when purpose not passed to verify() API.

### ISSUE THREAD

**Issue by gannan08** [digitalbazaar/jsonld-signatures#41]
We should be throwing an error if the purpose for the proof is not defined. This breaks backward compatibility and will force a major release.

**Comment by mattcollier** [comment]
Are we throwing if an unknown crytpo suite is utilized already?

**Comment by gannan08** [comment]
We are not doing that to the best of my knowledge.

**Comment by mattcollier** [comment]
Is an unknown `purpose` any different than `SomeUnknownSignatureScheme`?

Seems to me that in either case, we just {valid: false, error: new Error('unknown foo')}

**Comment by gannan08** [comment]
> Is an unknown `purpose` any different than `SomeUnknownSignatureScheme`?
> 
> Seems to me that in either case, we just return `{valid: false, error: new Error('unknown foo')}`

There would be no difference, the behavior should be the same.

**Comment by mattcollier** [comment]
@gannan08 so, you're proposing that `verify` throws?  This proposal goes against our recently adopted validator/verifier convention doesn't it?

**Comment by gannan08** [comment]
Ah, I'm guessing that when you said `SomeUnknownSignatureScheme` you meant a Signature suite like `Ed25519Signature2018`. I somehow misinterpreted `SomeUnknownSignatureScheme` to mean an uknown crypto suite.


> @gannan08 so, you're proposing that `verify` throws? This proposal goes against our recently adopted validator/verifier convention doesn't it?

Yes, `verify` should throw. In the future, not providing a purpose is a misuse of the API therefore we throw. We cannot validate the proof without the designated purpose.

**Comment by mattcollier** [comment]
I agree that the verify operation should return `{valid: false, error}`, why do we need to throw?

**Comment by mattcollier** [comment]
This is an instance where @dlongley would like to throw a `SyntaxErrror` with a *regular* API, but syntax errors are effectively what a verifier/validator is designed to detect and report using their return value `{valid, error}`.  That is the way I'm thinking about it.

**Comment by mattcollier** [comment]
In this case there is jsonld goodness happening to even determine what the proofPurpose value **is**.  And I believe you're suggesting that the calling code would need to make this determination *before* passing a document to the validator.  This means that there is a pre-validation step which doesn't seem right to me.  I think the pattern we're after is that validators just don't throw. <full stop>

**Comment by dlongley** [comment]
@mattcollier, I think it's unexpected for:

`jsonld.verify()` (intentionally no parameters)

To return `{valid: false, error}`. I think it should throw because it's a misuse of the API. There's no circumstance under which this would *ever* work. It's similar to a compile time error, IMO.

Failing a validator is not an exceptional event. It's a proper and expected result of calling the validator API. However, the above use is not "failing validation", rather, it is failing to use the API properly.

I think the validator return value semantics are: "Validation was run and the input was valid OR validation was run and the input was invalid -- see the errors for why." If we don't even get to run validation because the API was misused, that's an exception.

**Comment by dlongley** [comment]
So, to be clear, similar situations where you aren't passing enough information for the validation code to even attempt to run should raise exceptions. You're not using the API properly vs. you gave it everything it needed but the input was invalid.

**Comment by mattcollier** [comment]
are we talking about the `purpose` parameter to `verify` or are we talking about a missing `proofPurpose` in the document proof?  I'm talking about the latter which seems to be suggested by the title of this issue.

**Comment by dlongley** [comment]
> are we talking about the purpose parameter to verify or are we talking about a missing proofPurpose in the document proof? I'm talking about the latter which seems to be suggested by the title of this issue.

I thought we were talking about the former, not the latter. If it's the latter then I'm in agreement that that is a validation error and it should be returned in the return value. If we're talking about a missing `purpose` parameter to `verify`, it should be an exception.

**Comment by dlongley** [comment]
This is done now.
