### ISSUE TITLE
Use framing instead of compaction on verify input when JSON-LD bug is fixed.

### ISSUE THREAD

**Issue by gannan08** [digitalbazaar/jsonld-signatures#42]
https://github.com/w3c/json-ld-framing/issues/27

**Comment by gannan08** [comment]
https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/jsonld-signatures.js#L205-L232

**Comment by dlongley** [comment]
Framing will done be done, rather, the library assumes a proper data shape on input as part of the API contract. This avoids performing extra work that is usually unnecessary.
