### ISSUE TITLE
signing only the default graph

### ISSUE THREAD

**Issue by elf-pavlik** [digitalbazaar/jsonld-signatures#5]
1) I start with a document with a default and one named graph - http://tinyurl.com/z9ojfeq
2) I sign it - http://tinyurl.com/j257vsy
3) Now the normalized version of signed document doesn't have default graph any more, now it uses blank node identifier as name for the needs of signature - http://tinyurl.com/jaanxeh

Q: Does this signature also include content from graph named with `<https://bob.example/api?path=/card>` or just `_:c14n0` (originally the default graph)  ?

To allow server to add hypermedia controls using named graphs, as explained in http://ruben.verborgh.org/blog/2015/10/06/turtles-all-the-way-down/ I would like to have possibility to sign only the default graph on a client creating the content, server could also sign with different key other named graphs it adds to response but they could also have no signature.

**Comment by elf-pavlik** [comment]
Taking this example further
4) I rename graph named with blank node (former default graph) and used as subject for `sec:signature`, to use URI of a page as its name - http://tinyurl.com/jb3vbms
5) I move the signature to object inside of that named graph with `@id` same as the graph name (IRI of the web page) and normalized RDF stays exactly the same - http://tinyurl.com/heasa3b

I didn't try to verify this signature, but I guess I should have used named graph instead of default graph already in step 2 to keep the verification working.

@gkellogg do you see the behaviour of using graph name as the subject of `sec:signature` an intended behaviour? Does it also take into account cases where `@id` used for graph name appears also inside of the graph as `@id` of an entity described in that graph? As far as I remember document gets Normalized before verification so where the signature ended up during framing should not matter...

I also think about the ' the graph name is not required to denote the graph' peculiarity, and if it matters here - https://www.w3.org/TR/rdf11-concepts/#h_note_4

**Comment by elf-pavlik** [comment]
Thinking about signing documents serialized in formats which don't support graph names (Turtle & RDFa), maybe `@base` IRI could get used as subject of the signature?
I do understand that this repository focuses on JSON-LD. Since I plan to help with writing rdf-signatures module for [rdf-ext environment](https://github.com/rdf-ext/rdf-ext#modules), I feel interested in clarifying aspects mentioned above somewhere. Which online venue serves this such purpose?

**Comment by dlongley** [comment]
Hey @elf-pavlik, this is just a note that say we're not ignoring this issue, just haven't had the time to look into it yet.

**Comment by dlongley** [comment]
It's been a while since we looked into this. Ultimately, there's no plan to add API surface to sign specific portions of an input dataset -- whatever is input will be signed, with, of course, the exception of proof sets. How signing works is / will be detailed in the Data Integrity spec at W3C: https://w3c.github.io/vc-data-integrity/

Closing based on the above.
