### ISSUE TITLE
EcdsaKoblitzSignature2016 tests mix public keys and addresses dangerously

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/jsonld-signatures#52]
https://github.com/digitalbazaar/jsonld-signatures/blob/a636acd31bd9fdd0488c9e50a3e1a39500a2ce8a/tests/mock/keys.js#L50

Looking around I can see a couple instances of EcdsaKoblitzSignature2016, that support hex encoded public keys. 

IMO, `EcdsaKoblitzSignature2016` should not have anything to do with bitcoin, and reliance on bitcoin names or formats should be minimized.

`ecdsa-koblitz-pubkey:1LGpGhGK8whX23ZNdxrgtjKrek9rP4xWER` should be discouraged but remain supported, since tests are often what developers will look at it might be best to update to match https://json-ld.org/playground/ Signed with Bitcoin example.

`ecdsa-koblitz-pubkey:02234be9bcdf041f7530979b8b88b7dc62dd505a75883c8211f3a8250534f96dc0` 

A DID example: https://gist.github.com/Exulansis/903ab4a77b4173c2268f7a0ef90521ac#did-document-example

IMO the preferred public key format for EcdsaKoblitzSignature2016 should be `publicKeyHex`

Livenet addresses should be assumed for verification purposes.

**Comment by OR13** [comment]
@dlongley The DIF is finally working on a new signature suite to address many of the issues with `EcdsaKoblitzSignature2016`. Mostly upgrading to support the correct Linked Data Signature formats, and clarifying the signature algorithm. I'd like to take this opportunity to get something that is as close to RsaSignature2018 as possible (jws signatureValue + support for the correct property names). 

One thing I'm still concerned about is whether it is possible to create valid jws with ecdsa on secp256k1 curve. To my knowledge `ES256K-R` is not yet included JOSE algorithm registry. https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-es256k-signature

```
Note that while the secp256k1 curve itself is standard, the above names for the JWS algorithm and curve are not (yet) included in the JOSE algorithm registry.
```

This seems to be the key blocker for implementing a valid jws signature. 

https://github.com/decentralized-identity/lds-ecdsa-secp256k1-2019.js/issues/2

Assuming I can sort this out, I'd like to open a PR here to get this signature suite included in digitalbazaar/jsonld-signatures.

If you have any feedback or advice, I welcome your input.

**Comment by dlongley** [comment]
@OR13,

Sounds good! I hope you're able to get the JOSE algorithm registry updated ... I think there was a previous effort to do so but I guess it didn't pan out.

> Assuming I can sort this out, I'd like to open a PR here to get this signature suite included in digitalbazaar/jsonld-signatures.
> 
> If you have any feedback or advice, I welcome your input.

Actually, we're working to move the signature suites themselves out into their own repos and then have them depend on jsonld-signatures to provide the core API and any base classes. For example, we started moving EcdsaKoblitzSignature2016 over here: https://github.com/digitalbazaar/ecdsa-koblitz-signature-2016/tree/initial

We want to make it easier for suites to fix their own bugs and manage their own release cycles as well as allow frontend application code to be more selective in which suites the browser must download.

**Comment by OR13** [comment]
^ great approach.

**Comment by OR13** [comment]
I'm going to close this issue as its now opened on the incorrect repo.
