### ISSUE TITLE
`ControllerProofPurpose` should have the option to accept `publicKey` term

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/jsonld-signatures#66]
A controller document that specifies a key as being authorized as a `publicKey` (which means it can be used for any purpose that a public key can be used for) should not trigger an error when `ControllerProofPurpose` (or any derivatives) is used. It is more secure for a controller document to link public keys via specific proof purpose relations (i.e., authorize keys for specific purposes), but it isn't a hard requirement. So we need to fix up the framing call that only looks for a verification method (public key) under the specific proof purpose term and instead allow for the term `publicKey` as well.

**Comment by OR13** [comment]
@dlongley, thanks for this proof purpose work, its very useful.

It would be awesome to include in the README the signed JSON produced by:

```
const signed = await jsigs.sign(doc, {
  suite: new RsaSignature2018({key}),
  purpose: new AssertionProofPurpose()
});
```

As well as a link to the full spec that these rely on.

Its getting hard to tell what is valid "Linked Data Signatures 1.0" vs "new and experimental features that might be 2.0?", things like:

owner -> controller,
signature -> proof
creator -> verificationMethod

https://w3c-dvcg.github.io/ld-signatures/ (1.0) does not include any reference to Proof Purpose, verificationMethod, or controller, and uses the term signature and proof.

I see great value in these changes, but would love to be able to plan to support them, by planning to support a linked data signatures spec version, once its more stabilized... Mastodon already has issues with some of these changes.

**Comment by dlongley** [comment]
@OR13,

> It would be awesome to include in the README the signed JSON produced by:
> 
> ```
> const signed = await jsigs.sign(doc, {
>   suite: new RsaSignature2018({key}),
>   purpose: new AssertionProofPurpose()
> });
> ```
>
> As well as a link to the full spec that these rely on.

+1 to that. We just need to find the time to do it.

> As well as a link to the full spec that these rely on.
> 
> Its getting hard to tell what is valid "Linked Data Signatures 1.0" vs "new and experimental features that might be 2.0?", things like:
> 
> owner -> controller,
> signature -> proof
> creator -> verificationMethod

I completely sympathize with you. We've been too swamped to update the specs and we're trying to make some time for that in the very near future. Each of those changes are not "experimental" any more, the spec is just horribly out of date. All new LD proof methods should be using those new terms.

> I see great value in these changes, but would love to be able to plan to support them, by planning to support a linked data signatures spec version, once its more stabilized.

Those changes have now strongly preferred over the old terms, please do not use the old terms. Once there was a repo for the new OpenPgpSignature2019 (I think that was the name?) repo, I planned on commented and requesting the newer terms to be used.

**Comment by OR13** [comment]
@dlongley 

I'm the main developer on that https://github.com/transmute-industries/PROPOSAL-OpenPgpSignature2019

I've been looking at Mastodon, and thinking that the signature suite should look more like those signatures, but it sounds like I should be targeting more the look and feel of RsaSignature2018.

I'll cross link the issue and make the updates when I can, I'm following your lead here mostly, thats why the JSON examples are so valuable :)

**Comment by dlongley** [comment]
@OR13,

> ...but it sounds like I should be targeting more the look and feel of RsaSignature2018.

Yes, that's the way to go.

**Comment by dlongley** [comment]
Closing as already implemented, though the term that can be used is `verificationMethod` matching the modern DID core spec.
