### ISSUE TITLE
Signing and verifying a document to authenticate to a website: <<   I am not sure why the error is happening in the example here.

### ISSUE THREAD

**Issue by leehh312** [digitalbazaar/jsonld-signatures#70]
**Signed document: { '@context': { schema: 'http://schema.org/', action: 'schema:action' },
  action: 'AuthenticateMe',
  'https://w3id.org/security#proof':
   { '@graph':
      { '@type': 'https://w3id.org/security#Ed25519Signature2018',
        'http://purl.org/dc/terms/created': [Object],
        'https://w3id.org/security#challenge': 'abc',
        'https://w3id.org/security#domain': 'example.com',
        'https://w3id.org/security#jws':
         'eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..GHywrD9bxIP0_a580kathyOFBUlp3O8vuwMUzwTNH59eeDZh1-v-8uWWwoo31nezb_i4kDIjs2TLzJyoFKZQCw',
        'https://w3id.org/security#proofPurpose': [Object],
        'https://w3id.org/security#verificationMethod': [Object] } } }
Signature verification error: [ Error: Invalid signature.
      at Ed25519Signature2018.verifyProof (D:\nodejs workspace\jsonld_Test\node_modules\jsonld-signatures\lib\suites\LinkedDataSignature.js:162:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
      at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) ]**

I have an error in the signature validation part, but I do not know why the error occurred.

**Comment by mattcollier** [comment]
Please use `JSON.stringify(yourDocument, null, 2)` and the paste it into the issue using a code fence https://github.github.com/gfm/#code-fence

Some important details are being covered up by [Object]

Thank you.

**Comment by dlongley** [comment]
Closing as stale and lacking in information required to address it if it hasn't already been addressed.
