### ISSUE TITLE
Some CI Targets are failing

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/jsonld-signatures#71]
It appears that the `sodium-native` dependency is not building on the Node 6 target, should Node 6 be removed?

https://travis-ci.org/digitalbazaar/jsonld-signatures/builds/536920513?utm_source=github_status&utm_medium=notification

**Comment by davidlehn** [comment]
6.x support was removed months ago:
https://github.com/digitalbazaar/jsonld-signatures/commit/5eb276664fad3233eb509362babbc4f636475da9

**Comment by davidlehn** [comment]
Did you mean 12.x that the default "node" target is using?  I assumed they would resolve that upstream and our builds would fix themselves.  But it's taking quite a while.

**Comment by aljones15** [comment]
@mattcollier sodium native is used to generate ECDSA signatures. This branch addresses some of the issues:

https://github.com/digitalbazaar/jsonld-signatures/pull/67

**Comment by mattcollier** [comment]
Yes, I misread the log:
```
$ node --version
v12.3.1
$ npm --version
6.9.0
$ nvm --version
0.34.0
```

OK, now that I know this is for node 12, then this applies: https://github.com/sodium-friends/sodium-native/issues/95

So, can we disable the Node 12 target and start a corresponding issue until such time as it's fixed so we aren't just in the habit of ignoring CI failures?

**Comment by aljones15** [comment]
wow I was right about something today. Anyways we had discussed making sodium an optionalDependency with a replacement if it fails. it's a thorny issue was supposed to look into it, but have been to busy with http signatures.

**Comment by davidlehn** [comment]
@mattcollier It's a problem for every dependent package as well.  I didn't want to hack and then remember to unhack all the travis files due to a temporary (I assume) problem.  A reason to use that target was to find issues like this so I think we want to keep it around in general.

**Comment by mattcollier** [comment]
CI is green these days.  Closing.

**Comment by aljones15** [comment]
@mattcollier https://travis-ci.org/github/digitalbazaar/jsonld-signatures/jobs/712593634

I'm assuming this is being handled by @dmitrizagidulin at some point?
