### ISSUE TITLE
Fix Security Context Hosting and Documentation

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/jsonld-signatures#82]
I propose we change the ownership of https://www.npmjs.com/package/security-context

To not be `github.com/w3c-dvcg/security-vocab` and instead be digitalbazaar.

We should turn on github pages hosting for the repo above (after its ownership is changed), and use this repo as the central source of truth for jsonld security contexts.

If digitalbazaar will not host the security contexts and human documentation used for jsonld signatures, we should move to the ccg, but add some language around ownership and code responsibility, along with a process for addressing when documentation is marked as sufficiently out of date to warrant marking as deprecated.

Its not safe to recommend implementations with out of date documentation, we need to align incentives to fix this issue.

I'm happy to help with this.

**Comment by davidlehn** [comment]
To be clear, right now only Digital Bazaar people have maintainer access to the security-context package.  I imagine we're ok with having the source of that being under the digitalbazaar org.  But it's an open question what the best way to separate spec, docs, context, and packaging are.  For the DID context work it was initially all in the one repo, but we moved the npm parts out to https://github.com/digitalbazaar/did-context to avoid mixing spec work with context updates and packaging development.  That may be a direction to go here too.  Though there are tradeoffs with keeping things in sync to think about.

**Comment by OR13** [comment]
Yes, I agree, I'd like to see the contexts that matter to this npm module (and github repo) moved to a place that won't mark them as deprecated, and where we can drive collaboration around updating the human readable documentation for the contexts that this library and repo rely on. 

I'm not a member of the `w3c-dvcg` and AFAIK its not an active working group... leaving critical security contexts in it is sending a bad message, we need to have the contexts hosted in ccg or by you guys :)

I'd prefer to have the human readable documentation stored next to the context, in an npm module in the ccg... second best would be for you all to host it. 

If it stays in `w3c-dvcg` its very likely to get marked as deprecated, we should move it before that happens.

**Comment by davidlehn** [comment]
DVCG is a community group, not a working group.  As I understand, it is what we make of it.  There are a bunch of related repos in that org now.  Why do you say it's not active?  We still update repos there when we need to and have time.  What would you like to see happening?

**Comment by OR13** [comment]
https://github.com/w3c-ccg/community/issues/97

I want to address this issue.

**Comment by OR13** [comment]
This is now resolved, closing.
