### ISSUE TITLE
Add some protections around `sign` invocation

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/jsonld-signatures#87]
https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/suites/JwsLinkedDataSignature.js#L96

If the provided `sign` implementation fails silently and return `undefined` then this is currently throwing an obscure error in the base64 encoding routine that expects data to be an object etc.  I think we should test that a valid result has been returned before moving it along the pipeline and throw a meaningful error if not.

Also, since a signer may be associated with arbitrary code, this call should probably be wrapped and errors repackaged or suppressed in some way to provide useful errors and prevent potential leakage private data if a `signer` is not well implemented.

**Comment by dlongley** [comment]
Closing as now invalid.
