### ISSUE TITLE
controllerId is overriden in ControllerProofPurpose

### ISSUE THREAD

**Issue by gjgd** [digitalbazaar/jsonld-signatures#89]
The problem I'm facing happens at this line: https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/purposes/ControllerProofPurpose.js#L59

If the controller is an object here, `controllerId` gets set to `controller.id` but then is overriden by the whole `controller` object.

This causes this line to fail later on: https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/purposes/ControllerProofPurpose.js#L72

I think the condition should look something like this instead:
```js
if(typeof controller === 'object') {
  controllerId = controller.id;
} else if(typeof controller !== 'string') {
  throw new TypeError("controller" must be a string representing a URL.');
} else {
  controllerId = controller;
}
```

**Comment by aljones15** [comment]
@davidlehn @dlongley just to make sure controller can not be Array<string> of ids?
According to the [DiD Spec:](https://w3c.github.io/did-core/#dfn-did-controllers)

> DID controller
> The entity that has the ability to make changes to a DID document. A DID can have more than one controller. The DID controller(s) are denoted by the controller property on the top level of the DID document. Note that the DID controller(s) might include the DID subject.

So I believe in the case where a DiD has multiple controllers it might be an Array<string> or Array<object> Anyways @gjgd thanks for the issue and I am adding a unit test for this case right now. I will also add a commit with your fix, but it looks like it might need review as I think we might need to handle the case where a controller is an array, but I could be wrong.

**Comment by aljones15** [comment]
@gjgd can you confirm if this is the error you are getting:

```
{ valid: false,
  error:
   { JsonLdError [jsonld.SyntaxError]: Invalid JSON-LD syntax; "@id" value an empty object or array of strings, if framing
       at _expandObject (/work/ajones/digital_bazaar/jsonld-signatures/node_modules/jsonld/lib/expand.js:480:19)
       at api.expand (/work/ajones/digital_bazaar/jsonld-signatures/node_modules/jsonld/lib/expand.js:246:9)
     name: 'jsonld.SyntaxError',
     details: { code: 'invalid @id value', value: [Object] } } }
```

**Comment by gjgd** [comment]
@aljones15  That's correct

**Comment by dlongley** [comment]
It really seems like the code is missing an `else` like @gjgd suggested. Clearly we're missing tests for this as well. +1 to a PR that addresses this. Also, looks like the same bug would happen with the deprecated `owner` param. Note: I think supporting controller arrays is a separate issue from this one -- we should get this fixed.

**Comment by aljones15** [comment]
closing as PR has been merged thanks for the bug report.
