### ISSUE TITLE
Post Install fix for 4.6.0

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/jsonld-signatures#95]
`"postinstall": "sed -i.bak 's/         controllerId = controller;/else{controllerId = controller}/g' node_modules/jsonld-signatures/lib/purposes/ControllerProofPurpose.js"`

I think this may be needed in the latest version.

**Comment by OR13** [comment]
@gjgd can you elaborate / cross link any related issues.

**Comment by gjgd** [comment]
Same as https://github.com/digitalbazaar/jsonld-signatures/issues/89

**Comment by OR13** [comment]
closing dupe
