### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: A URL "https://www.w3.org/ns/did/v1" could not be fetched; you need to pass "documentLoader" or resolve the URL before calling

### ISSUE THREAD

**Issue by zhanb** [digitalbazaar/jsonld-signatures#97]
(node:29197) UnhandledPromiseRejectionWarning: Error: A URL "https://www.w3.org/ns/did/v1" could not be fetched; you need to pass "documentLoader" or resolve the URL before calling "sign".
    at Object.sign (/root/did/json-ld-signature/node_modules/jsonld-signatures/lib/jsonld-signatures.js:26:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:29197) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:29197) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aljones15** [comment]
the issue here is the `documentLoader` could not dereference the url for your did json-ld context. You can pass in a `documentLoader` as a parameter to sign.

**Comment by mandyvenables** [comment]
@zhanb Does the comment above answer your question? If so, please close the issue. Thanks!
