### ISSUE TITLE
LinkedDataSignature.getVerificationMethod limited to w3id.org security context definitions.

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/jsonld-signatures#98]
Related: https://github.com/digitalbazaar/jsonld.js/issues/392

https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/suites/LinkedDataSignature.js#L233

This prevents suite implementers from relying on the base class, and forces them to comprehend JSON-LD and implement their own `getVerificationMethod`... here is one example:

```
async getVerificationMethod({ proof, documentLoader }) {
    if (this.key) {
      return this.key.publicNode();
    }
    // replaces:
    // const verificationMethod = await super.getVerificationMethod({
    //   proof,
    //   documentLoader,
    // });
    // Because hard coding security contexts prevents extension using base class
    // https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/suites/LinkedDataSignature.js#L233
    let controller = (await documentLoader(proof.verificationMethod)).document;
    const verificationMethod = await jsonld.frame(
      controller,
      {
        "@context": [
          "https://w3id.org/security/v2",
          "https://identity.foundation/EcdsaSecp256k1RecoverySignature2020/lds-ecdsa-secp256k1-recovery2020-0.0.jsonld",
        ],
        "@embed": "@always",
        id: proof.verificationMethod,
      },
      { documentLoader, compactToRelative: false }
    );
    await this.assertVerificationMethod({ verificationMethod });
    return verificationMethod;
  }
```

Perhaps this is by design... but its feels a bit odd.

**Comment by OR13** [comment]
seems natural that if you are building a new suite, you probably don't want to use w3id.org... because it won't have your new suite.

**Comment by OR13** [comment]
Recommendation is to do 1 of 2 things... 

1. overwrite security-v2 (if you can) --- only do this to test what the future will look like.
2. put you context on the input document, and DO NOT use compactProof: true

**Comment by dlongley** [comment]
@OR13 -- I edited your comment to say "DO NOT use compactProof: false" instead of "true". I probably should have just made this comment instead, apologies.

**Comment by dlongley** [comment]
Related to fixing the confusing polarity on "compactProof": https://github.com/digitalbazaar/jsonld-signatures/issues/107

**Comment by OR13** [comment]
thanks! I actually prefer the edit in this case!

**Comment by dlongley** [comment]
I believe this has been fixed, closing.
